---
layout: cv
title: Ryan Lee History
---
# Ryan Lee
College Student

<div id="webaddress">
<a href="https://www.linkedin.com/in/ryan-lee-99824b323/">LinkedIn Page</a>
| <a href="https://github.com/YesterFence">My Github page</a>
</div>


## Currently

Studying at Brigham Young University - Idaho

### Specialized in

Computer Science with an emphasis in Machine Learning


### Research interests

Cyber Security, Machine Learning, Algorithms


## Education


`Nov 2022 - Apr 2024`
__COMC LLC__

- Warehouse Order Fulfillment Team

`2022 - Now`
__Brigham Young University - Idaho__



## Awards

`2025`
SysSec+ Comptia Certificate

Associates in Computer Science



## Projects

__Multiplayer Freeze Tag Game__

- Team built a game that relied on Web Sockets from node.js and the Godot game engine

__Sudoku Solver__

- Automated Sodoku Solver using recursion with Erlang

__Wardrobe App__

- A closet and clothing organizer with React Native

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->


## Skills

- Adaptability, Algorithms, API Programming, Bash Scripting, C#, C++, Cisco Packet Tracer, CSS, Database Management, Erlang, GitHub, HTML, Java, JavaScript, Linux Scripting, Linux Terminal, Microsoft Excel, Microsoft Word, Problem Solving, Python, Quarto, React.js, Scrum, Software Programming, SQL (Structured Query Language), Ubuntu, Virtual Machines, Web Development, Windows OS



<!-- ### Footer

Last updated: Dec 2025 -->